---
- hosts: all
#  connection: local
  gather_facts: yes
  become: true
  tasks:
    - name: add golang ppa
      apt_repository:
        repo: "ppa:longsleep/golang-backports"
    - name: update /etc/environment
      copy:
        src: "fixtures/environment"
        dest: /etc/environment
        owner: root
        group: root
        mode: 0644
        force: yes
    - name: install apt deps
      shell: |
        apt-get update
        apt-get install -qyf \
          build-essential \
          fakeroot \
          curl \
          dh-systemd \
          debhelper \
          gcc \
          make \
          golang-1.15 \
          golang \
          ubuntu-dev-tools \
          wget
    - name: copy bashrc
      copy:
        src: "fixtures/bashrc"
        dest: /root/.bashrc
        owner: root
        group: root
        mode: 0644
        force: yes
    - name: copy ssh creds
      copy:
        src: "{{ lookup('env', 'CDKBOTSSHCREDS') }}"
        dest: /root/.ssh/cdkbot_rsa
        owner: root
        group: root
        mode: 0600
        force: yes
    - name: copy gpg public key
      copy:
        src: "{{ lookup('env', 'K8STEAMCI_GPG_PUB') }}"
        dest: /root/gpg-pub.key
        owner: root
        group: root
        mode: 0644
    - name: copy gpg private key
      copy:
        src: "{{ lookup('env', 'K8STEAMCI_GPG_PRIVATE') }}"
        dest: /root/gpg-private.key
        owner: root
        group: root
        mode: 0644
    - name: import gpg keys
      ignore_errors: yes
      shell: |
        gpg --batch --import gpg-pub.key
        gpg --batch --import gpg-private.key
    - name: clone jenkins repo
      shell: |
        git clone https://github.com/charmed-kubernetes/jenkins
    - name: run build
      shell: |
        export CDKBOT_GH_USR="{{ lookup('env', 'CDKBOT_GH_USER') }}"
        export CDKBOT_GH_PSW="{{ lookup('env', 'CDKBOT_GH_PSW') }}"
        pip3 install -rrequirements.txt
        python3 jobs/build-debs/build-debs.py build-debs \
              --version "{{ lookup('env', 'K8S_VERSION') }}"
      args:
        chdir: /root/jenkins
