---
- hosts: localhost
  connection: local
  gather_facts: yes
  become: true
  tasks:
    - sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes
    - name: install apt deps
      apt:
        name:
          - ubuntu-server
          - ubuntu-standard
          - sosreport
          - build-essential
          - ubuntu-dev-tools
          - gcc
          - strace
          - make
          - curl
          - file
          - wget
          - docker.io
          - unzip
          - python3-pip
          - flake8
          - squashfuse
          - snapd
          - libffi6
          - libffi-dev
          - libssl-dev
          - default-jre
          - snapcraft
    - name: remove unused debs
      apt:
        name:
          - python-pip
          - juju
          - lxd
          - lxd-client
          - lxcfs
          - lxc-common
          - liblxc1
        state: absent
    - name: install snap deps
      command: "snap install {{item}}"
      ignore_errors: yes
      loop:
        - "lxd"
        - "juju --classic"
        - "juju-wait --classic"
        - "kubectl --classic"
        - "charm --classic --edge"
    - name: checkout juju-wait source
      when: ansible_architecture != "x86_64"
      git:
        repo: https://git.launchpad.net/juju-wait.git
        dest: /srv/juju-wait
    - name: check for existing juju-wait snap
      command: "snap info juju-wait | grep -q 'installed'"
      register: juju_wait_out
    - name: build juju-wait source
      when: ansible_architecture != "x86_64" or juju_wait_out.status > 0
      command: "snapcraft build && snap install juju_wait*snap"
      args:
        chdir: /srv/juju-wait
    - name: copy bashrc
      copy:
        src: "bashrc"
        dest: /var/lib/jenkins/.bashrc
        owner: jenkins
        group: jenkins
        mode: 0644
        force: yes
    - name: copy charm creds
      copy:
        src: "{{charm_creds}}"
        dest: /var/lib/jenkins/.go-cookies
        owner: jenkins
        group: jenkins
        mode: 0644
        force: no
    - name: login to charmstore
      command: "charm login"
      become: false
    - name: copy snapcraft creds
      copy:
        src: "{{snapcraft_creds}}"
        dest: /var/lib/jenkins/snapcraft-creds
        owner: jenkins
        group: jenkins
        mode: 0644
        force: no
    - name: login to snapstore
      command: "snapcraft login --with /var/lib/jenkins/snapcraft-creds"
      become: false
    - name: create juju dir
      file:
        path: /var/lib/jenkins/.local/share/juju
        state: directory
        mode: 0755
    - name: copy juju credentials
      unarchive:
        src: "{{juju_creds}}"
        dest: /var/lib/jenkins/.local/share/juju
    - name: set perms
      file:
        path: /var/lib/jenkins/.local/share/juju
        owner: jenkins
        group: jenkins
        recurse: yes
    - name: update jenkins user
      user:
        name: jenkins
        groups: jenkins,docker,lxd
    - name: setup lxd network
      command: "/snap/bin/lxd init --auto"
