meta:
  name: CI Infrastructure
  description: Provides support tasks for maintaining Jenkins

plan:
  - script:
      - tox -e ansible
  # - script:
  #     - |
  #       #!/bin/bash

  #       set -eux

  #       # tox -e ansible -- ansible-playbook jobs/infra/playbook-jenkins.yml \
  #       #   -e 'ansible_python_interpreter=/usr/bin/python3.5' \
  #       #   --limit localhost \
  #       #   --tags 'jenkins' \
  #       #   -i jobs/infra/hosts
  #       tox -e ansible
