---
- hosts: all
#  connection: local
  gather_facts: yes
  become: true
  tasks:
    - name: install apt deps
      apt:
        name:
          - apache2
          - apt-mirror
          - simplestreams
          - squid
    - name: remove unused debs
      apt:
        name:
          - juju
          - lxd
          - lxd-client
          - lxcfs
          - lxc-common
          - liblxc1
        state: absent
    - name: install snap deps
      command: "snap install {{item}}"
      ignore_errors: yes
      loop:
        - "juju --classic --channel latest/stable"
        - "juju-wait --classic"
        - "lxd"
    - name: update ubuntu user
      user:
        name: ubuntu
        groups: lxd
    # - name: reset ssh connection
    #   meta: reset_connection
    - name: setup lxd network
      command: "/snap/bin/lxd init --auto"
      ignore_errors: yes
      become: false
    - name: disable ipv6 in lxd
      become: false
      command: "lxc network set {{item}} ipv6.address none"
      loop:
        - 'lxdbr0'
        - 'lxdbr1'
      ignore_errors: true
    - name: import local lxd images
      become: false
      command: "lxc image copy ubuntu:{{item}} local: --copy-aliases"
      loop:
        - '18.04'
        - '16.04'
        - '14.04'
    - name: copy mirror list
      copy:
        src: "fixtures/apt-mirror.list"
        dest: /etc/apt/mirror.list
        owner: root
        group: root
        mode: 0644
        force: yes

    - name: setup apache mirror
      copy:
        src: "fixtures/apache-ubuntu-mirror.conf"
        dest: /etc/apache2/sites-available/ubuntu-mirror.conf
        owner: root
        group: root
        mode: 0644
        force: yes
    - name: enable mirror site
      command: a2ensite ubuntu-mirror.conf
    - name: restart apache
      command: systemctl restart apache2

    - name: sync apt mirror
      command: apt-mirror

    # Run this after squid is setup so that juju will refer to our local proxy
    # for blocking out external services
    # - name: update /etc/environment
    #   copy:
    #     src: "fixtures/environment"
    #     dest: /etc/environment
    #     owner: root
    #     group: root
    #     mode: 0644
    #     force: yes
