---
- hosts: all
  gather_facts: yes
  become: true
  tasks:
    - name: update /etc/environment
      copy:
        src: "files/environment"
        dest: /etc/environment
        owner: root
        group: root
        mode: 0644
        force: yes
    - name: remove unused debs
      apt:
        name:
          - juju
          - lxd
          - lxd-client
          - lxcfs
          - lxc-common
          - liblxc1
        state: absent
    - name: add necessary debs
      apt:
        name:
          - libffi-dev
          - python3-dev
    - name: install snap deps
      command: "snap install {{item}}"
      ignore_errors: yes
      loop:
        - "juju --classic --stable"
        - "juju-wait --classic"
        - "juju-crashdump --classic --edge"
        - "lxd --candidate"
    - name: update ubuntu user
      user:
        name: ubuntu
        groups: lxd
    - name: reset ssh connection
      meta: reset_connection
    - name: setup lxd network
      command: "/snap/bin/lxd init --auto"
      ignore_errors: yes
      become: false
    - name: disable ipv6 in lxd
      become: false
      shell: |
        export PATH=/snap/bin:$PATH
        # lxc profile device remove default eth0
        # lxc profile device add default eth0 nic name=ens5 nictype=bridged parent=lxdbr0
        # lxc network set lxdbr0 ipv4.nat true
        # lxc network set lxdbr0 ipv4.dhcp true
        lxc network set lxdbr0 ipv6.address none
      ignore_errors: true
    - name: grab jenkins ci repo
      command: "git clone https://github.com/charmed-kubernetes/jenkins"
      become: false
    - name: install python deps
      become: true
      shell: |
        pip3 install pip-tools
        pip-sync
      args:
        chdir: jenkins
